# Header
navname: "知りたいままに | Xin's Notebook"

# navigatior items
nav:
  Posts: /archives
  Categories: /category
  Tags: /tag
  About: /about

# favicon
favicon: /image/avatar.png
# Profile
nickname: Xin's Notebook

### this variable is MarkDown form.
description: "<em>Nice to meet you.</em>"
avatar: /image/avatar.png

# main menu navigation
## links key words should not be changed.
## Complete url after key words.
## Unused key can be commented out.
links:
  Blog: /archives
  # Category:
  # Tags: 
  # Link:
  # Resume:
  # Publish:
  # Trophy:
  # Gallery:
  # RSS:
  # AliPay:
  # ZhiHu: 
  LinkedIn: https://www.linkedin.com/in/arriettyc/
  # FaceBook:
  # Twitter:
  # Skype:
  # CodeSandBox:
  # CodePen:
  # Sketch:
  # Gitlab:
  # Dribbble:
  # Instagram:
  # Reddit:
  # YouTube:
  # QQ:
  # Weibo:
  # WeChat:
  Github: https://github.com/arriettyc

# how links show: you have 2 choice--text or icon.
links_text_enable: false
links_icon_enable: true

# Post page
## Post_meta
post_meta_enable: true

post_author_enable: true
post_date_enable: true
post_category_enable: true
## Post copyright
post_copyright_enable: true

post_copyright_author_enable: true
post_copyright_permalink_enable: true
post_copyright_license_enable: true
post_copyright_license_text: Copyright (c) 2019 <a href="http://creativecommons.org/licenses/by-nc/4.0/">CC-BY-NC-4.0</a> LICENSE
post_copyright_slogan_enable: false
post_copyright_slogan_text: Do you believe in <strong>DESTINY</strong>?
## toc
post_toc_enable: true

# Page
page_title_enable: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMMM D, YYYY
time_format: H:mm:ss

# stylesheets loaded in the <head>
stylesheets:
  - /css/style.css

# scripts loaded in the end of the body
scripts:
  - /js/script.js
  - /js/tocbot.min.js
    # tscanlin/tocbot: Build a table of contents from headings in an HTML document.
    # https://github.com/tscanlin/tocbot

# Markdown
markdown_it:
  html: true # Allow HTML tags (important for MathJax to inject its elements)
  xhtmlOut: false
  breaks: true # Set to false if you still see <br> tags within math blocks after this fix
  langPrefix: lang-
  linkify: true
  typographer: true
  quotes: '“”‘’'
  plugins:
    - markdown-it-mathjax3 # Enable the mathjax3 plugin for markdown-it

# Existing Math Formulas Render Support from your image_450a05.png:
math:
  per_page: true # Keep this if you want math only on specific posts.

mathjax:
  enable: true # Keep this. Your theme likely uses this to conditionally load MathJax.
  import: demand

katex:
  enable: false # Ensure KaTeX is disabled
  copy_tex: false